
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: kanboard
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    pid /var/run/nginx.pid;

    events {
      worker_connections 1024;
    }
    http {
      include       mime.types;
      default_type  application/octet-stream;

      sendfile           on;
      tcp_nopush         on;
      tcp_nodelay        on;
      keepalive_timeout  65;
      server_tokens      off;
      access_log         off;
      error_log          /dev/stderr;

      fastcgi_buffers 16 16k;
      fastcgi_buffer_size 32k;

      server {
        listen                  80 default_server;
        listen                  [::]:80 default_server;

        server_name             localhost;
        index                   index.php

        # Set nginx to serve files from the shared volume
        client_max_body_size    32M;

        location / {
          try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php$ {
          root /app/;
          # try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;

          fastcgi_pass 127.0.0.1:9000;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param SERVER_NAME $host;
          include fastcgi_params;
          fastcgi_index index.php;

        }

        location ~ /data {
            return 404;
        }

        location ~* ^.+\.(log|sqlite)$ {
            return 404;
        }

        location ~ /\.ht {
            return 404;
        }

        location ~* ^.+\.(ico|jpg|gif|png|css|js|svg|eot|ttf|woff|woff2|otf)$ {
            root /var/www/app/;
            log_not_found on;
            expires 7d;
            etag on;
        }

        gzip on;
        gzip_comp_level 3;
        gzip_disable "msie6";
        gzip_vary on;
        gzip_types
            text/javascript
            application/javascript
            application/json
            text/xml
            application/xml
            application/rss+xml
            text/css
            text/plain;
      }
    }
...