---
# Using the 32123 port to make the app accessible
apiVersion: v1
kind: Service
metadata:
  name: kanboard-service
  namespace: kanboard
spec:
  type: NodePort
  selector:
    app: kanboard-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32123

...